TokenManager:
  bilibili:
    headers:
      'accept-language': zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
      'origin': https://www.bilibili.com
      'referer': https://space.bilibili.com/
      'origin_2': https://space.bilibili.com
      'cookie': buvid3=287CA283-467A-0AAD-484A-69F5E28BDB4901442infoc; b_nut=1765837801; b_lsid=BCECE10A8_19B2422935D; _uuid=F5A6109910-961F-75D5-5C18-BC45F3DC1088D04412infoc; home_feed_column=4; bmg_af_switch=1; bmg_src_def_domain=i0.hdslb.com; buvid4=C0C347C6-F555-0F80-026B-19BDD0CEA08103299-025121606-NH3wkd/dfGQ77ppB4VrW1g%3D%3D; bili_ticket=eyJhbGciOiJIUzI1NiIsImtpZCI6InMwMyIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjYwOTcwMDMsImlhdCI6MTc2NTgzNzc0MywicGx0IjotMX0.E6jf020B7eTgat3x9T0eMV6Lk-JdZsSnxfQ8kbC49Ho; bili_ticket_expires=1766096943; buvid_fp=cbe3bbfc2022b17782a4e67f05fc5cec; SESSDATA=4be5c2d0%2C1781389846%2Cfb494%2Ac1CjCclp68nup7rPRFqKJvWzsGk85_JuUlQlvkYx-OiHk1XqdCBaORJCvz0m9rCdahZdESVlZMNDhBTXItZHc0TE9rZUd5enNuQzh3U2ZvNEFLaTZzWlB6Qjg0MzNlRWt0NV9BcWRwYjk1TS1GSldaRUxUcThtcEIwRlZhUkptX3J1V2EyQVpjOVFnIIEC; bili_jct=e5443a6a4ff42f7d3973d703c6d08220; DedeUserID=515396342; DedeUserID__ckMd5=53eac243a559e975; CURRENT_FNVAL=2000; browser_resolution=491-762; sid=5i7axmr3
      'user-agent': Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36

    proxies:
      http:
      https:
